name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.LINY_TOKEN }}
          issue-message: "Hello, thanks for opening your first issue! "
          pr-message: "Hello, thanks for opening your first PR! "
